### ISSUE TITLE
How to hide preview panel

### ISSUE THREAD

**Issue by bianyifan** [tylingsoft/markdown-plus#54]
How to hide preview panel ,use javascript?I don't want preview panel is displaying on page load.It's unfriendly to mobile user.

**Comment by tylerlong** [comment]
I don't think Markdown Plus works with mobile devices, because I never tested that.

For you question, please check the screenshot:

![screen shot 2016-02-29 at 10 27 49 am](https://cloud.githubusercontent.com/assets/733544/13384294/2d4f6222-decf-11e5-8284-64b8249a3ccc.png)

If you want some js code, here it is:

``` js
layout.sizePane('east', 1);
```

**Comment by bianyifan** [comment]
Markdown Plus can work on the mobile devices,but toolbar just have 3 lines, need scrool.
