### ISSUE TITLE
How to show preview only without tools bar and editor

### ISSUE THREAD

**Issue by Braraear** [tylingsoft/markdown-plus#67]
If I don't want somebody edit it.

**Comment by tylerlong** [comment]
If you are a programmer, you are probably interested in this project: https://github.com/tylingsoft/markdown-core  This project provides markdown engine to generate HTML for preview. Since you don't need toolbar and editor, this project is more suitable.

Or if you want a quick-and-dirty solution:

![screen shot 2016-06-01 at 5 35 08 pm](https://cloud.githubusercontent.com/assets/733544/15704895/41f0ede2-281f-11e6-8be3-cf9df687d9a2.png)

Or by code:
1. hide toolbar: https://github.com/tylingsoft/markdown-plus/blob/master/markdown-plus.js#L30
2. hide editor: https://github.com/tylingsoft/markdown-plus/blob/master/markdown-plus.js#L35
   1. set east panel size to '100%'

**Comment by Braraear** [comment]
Thanks you, I'm following your upldate
