### ISSUE TITLE
Blog Content by markdown-plus

### ISSUE THREAD

**Issue by Braraear** [tylingsoft/markdown-plus#71]
I want to create blog system and use markdown-core for display my markdown files

and can I use markdown-plus to edit .md file and save it ? last one how to use markdown-plus plugin

autosave because I not seem a textarea. Sorry for my bad language because it not my own language

**Comment by tylerlong** [comment]
`markdown-core` itself is sufficient for a blog system. You don't need `markdown-plus`.

For edit and save .md on your computer, you need to use the `markdown-plus` app: http://tylingsoft.com/markdown-plus/  The app is not free, unfortunately.  

For autosave, there is a plugin: https://github.com/tylingsoft/markdown-plus-plugins The plugin is for the desktop app instead of the web version.

**Comment by Braraear** [comment]
Can I make edit and save .md on browser ?

**Comment by tylerlong** [comment]
Nope. That's not possible with client side JS code. Browser doesn't allow you to read/write hard disk directly. What you can do is to upload/download instead.

**Comment by Braraear** [comment]
Okay thanks for your answer ;)
