### ISSUE TITLE
sequenceDiagram arrowhead disappeared in exported html

### ISSUE THREAD

**Issue by Bryant-Yang** [tylingsoft/markdown-plus#72]
I'm using markdown plus app purchased on AppStore.

Create new md file, write more than one sequenceDiagram and export to html, open it in browser, you could see the arrowheads are missing except the last one.  While pdf export is correct.

> ```
> sequenceDiagram
> a->>b: the arrowhead is missing
> ```
> ```
> sequenceDiagram
> c->>d: only the last one is ok
> ```

购买的markdown plus，画多个序列图，导出成html，只有最后一个序列图有箭头，之前的只剩横线没有箭头了。

**Comment by tylerlong** [comment]
Sorry man, I was in vacation this week and didn't see your message. Let me check it and get back to you later.

**Comment by tylerlong** [comment]
Yes I confirm this is a bug. Here is a quick workaround: https://github.com/tylingsoft/markdown-plus-plugins

Please install the plugin "SVG charts in exported HTML" and try again. With this plugin the diagrams are exported as SVG instead of PNG.

In the next release, diagram in HTML will be by default in SVG format.

**Comment by Bryant-Yang** [comment]
The workaround is doing well, and I keep this issue open till the new version updated.

**Comment by Bryant-Yang** [comment]
fixed in 2.1.0 (25)
