### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by okwolf** [tylingsoft/markdown-plus#85]
[It's available](https://www.npmjs.com/package/markdown-plus).

This will make reusing the existing demo much easier. Please include at least the latest tag/release (2.2.1 as of now).

If you're not interested in doing it yourself but don't mind me doing the publish, let me know.

**Comment by tylerlong** [comment]
The core part is published as npm package `markdown-core`.  `markdown-plus` is more about UI.

If the only purpose is to make demo easier, I doubt that's the right way to take advantages of npm. Let me think about it.

By the way, currently the project is broken due to lots of work I did yesterday. I will fix it today.

**Comment by tylerlong** [comment]
Done.

You can also compile it yourself:

```
yarn install
yarn build
host and open dist/index.html
```
